---
driver:
  require_chef_omnibus: 12.18.31
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: ubuntu/xenial64
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[playground::default]
    attributes:
