---
driver:
  require_chef_omnibus: 12.18.31
  name: vagrant #docker
  use_sudo: false
  vagrantfiles:
    - .kitchen.vagrant-config.rb

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: ubuntu/xenial64
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[chef_starter::default]
    attributes:
